import { Crown, ShieldCheck, Sparkles } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { PLANS, formatPlanPrice, type PlanCode } from '@/lib/subscriptions/plans';

export default function AdminPlansPage() {
  return <div className="space-y-7">
    <div><p className="text-sm font-semibold text-primary">Revenue & access</p><h1 className="mt-1 text-3xl font-bold text-slate-800">Plans & Pricing</h1><p className="mt-2 text-slate-500">Launch pricing and the entitlement foundation used across CupidMatch.</p></div>
    <div className="grid gap-5 lg:grid-cols-3">{(Object.keys(PLANS) as PlanCode[]).map(code => { const p=PLANS[code]; return <Card key={code} className="rounded-2xl"><CardHeader><CardTitle className="flex items-center justify-between"><span>{p.name}</span><span className="text-primary">{formatPlanPrice(p.pricesPence.monthly)}{p.pricesPence.monthly ? '/mo' : ''}</span></CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-slate-600"><div className="rounded-xl bg-slate-50 p-3"><div>1 month: {formatPlanPrice(p.pricesPence.monthly)}</div><div>3 months: {formatPlanPrice(p.pricesPence.three_months)}</div><div>6 months: {formatPlanPrice(p.pricesPence.six_months)}</div></div><div className="flex items-center gap-2"><Sparkles className="h-4 w-4"/> Interests: {p.entitlements.interestsPerMonth ?? 'Unlimited*'}</div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4"/> Shares: {p.entitlements.profileSharesPerMonth ?? 'Unlimited*'}</div><div className="flex items-center gap-2"><Crown className="h-4 w-4"/> Boosts: {p.entitlements.profileBoostsPerMonth}/month</div><div>Full compatibility: {p.entitlements.fullCompatibility ? 'Enabled' : 'Basic only'}</div><div>Advanced filters: {p.entitlements.advancedFilters ? 'Enabled' : 'Free basics only'}</div><div>Profile visitors: {p.entitlements.seeProfileVisitors ? 'Visible' : 'Locked'}</div><div>Family Introduction: {p.entitlements.familyIntroduction ? 'Enabled' : 'Locked'}</div><div>Incognito: {p.entitlements.incognitoMode ? 'Enabled' : 'Locked'}</div><div>Priority visibility: {p.entitlements.priorityVisibility ? 'Enabled' : 'Standard'}</div></CardContent></Card> })}</div>
    <Card><CardHeader><CardTitle>Management status</CardTitle></CardHeader><CardContent className="text-sm text-slate-600">Paid access must be activated by verified billing state on the server. UI plan labels never grant an entitlement by themselves. Unlimited features remain subject to anti-spam and safety controls.</CardContent></Card>
  </div>;
}
