export const BILLING_ENV_NAMES = [
  'STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','STRIPE_PRICE_PREMIUM_MONTHLY','STRIPE_PRICE_PREMIUM_3_MONTHS','STRIPE_PRICE_PREMIUM_6_MONTHS','STRIPE_PRICE_PREMIUM_PLUS_MONTHLY','STRIPE_PRICE_PREMIUM_PLUS_3_MONTHS','STRIPE_PRICE_PREMIUM_PLUS_6_MONTHS',
] as const;
