"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Promo={id:string;code_hint:string;duration_months:number;max_redemptions:number;redemption_count:number;expires_at:string|null;is_active:boolean;created_at:string};
type Redemption={id:string;promo_code_id:string;user_id:string;member_name:string;redeemed_at:string;trial_ends_at:string};
export default function PromoCodesClient(){
 const [editing,setEditing]=useState<string|null>(null),[editLimit,setEditLimit]=useState(100),[editExpiry,setEditExpiry]=useState("");
 const [months,setMonths]=useState(6),[limit,setLimit]=useState(100),[expiry,setExpiry]=useState("");
 const [redemptions,setRedemptions]=useState<Redemption[]>([]);
 const [codes,setCodes]=useState<Promo[]>([]),[created,setCreated]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch("/api/admin/promo-codes",{cache:"no-store"});if(!r.ok)throw Error("Could not load codes");const data=await r.json();setCodes(data.codes||[]);setRedemptions(data.redemptions||[]);}catch(e){setError(e instanceof Error?e.message:"Load failed");}}
 useEffect(()=>{void load();},[]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setCreated("");setError("");try{const r=await fetch("/api/admin/promo-codes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({durationMonths:months,maxRedemptions:limit,expiresAt:expiry||null})});const data=await r.json();if(!r.ok)throw Error(data.error||"Creation failed");setCreated(data.code);await load();}catch(e){setError(e instanceof Error?e.message:"Creation failed");}finally{setBusy(false);}}
 async function toggle(id:string,isActive:boolean){setError("");setBusy(true);try{const r=await fetch("/api/admin/promo-codes",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,isActive})});if(!r.ok)throw Error((await r.json()).error||"Could not update code");await load();}catch(e){setError(e instanceof Error?e.message:"Could not update code");}finally{setBusy(false);}}
 async function saveLimits(){if(!editing)return;setError("");setBusy(true);try{const r=await fetch("/api/admin/promo-codes",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editing,maxRedemptions:editLimit,expiresAt:editExpiry||null})});if(!r.ok)throw Error((await r.json()).error||"Could not save limits");setEditing(null);await load();}catch(e){setError(e instanceof Error?e.message:"Could not save limits");}finally{setBusy(false);}}
 return <div className="space-y-6">
 <div><p className="text-sm font-semibold text-violet-700">Member growth</p><h1 className="text-3xl font-bold text-slate-900">Special invitation codes</h1><p className="mt-2 text-slate-600">Create limited-use launch codes. New members can enter a code during registration.</p></div>
 <form onSubmit={create} className="grid gap-4 rounded-3xl border bg-white p-6 shadow-sm md:grid-cols-3">
 <label className="text-sm font-medium">Trial duration (months)<Input type="number" min={1} max={24} required value={months} onChange={e=>setMonths(Number(e.target.value))}/></label>
 <label className="text-sm font-medium">Maximum redemptions<Input type="number" min={1} max={100000} required value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label>
 <label className="text-sm font-medium">Expiry date (optional)<Input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label>
 <div className="md:col-span-3"><Button disabled={busy} type="submit">{busy?"Creating…":"Generate secure code"}</Button></div>
 </form>
 {created&&<div role="status" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-semibold">New code — copy it now; it will not be shown again</p><p className="my-3 break-all font-mono text-xl">{created}</p><Button variant="outline" onClick={()=>void navigator.clipboard.writeText(created)}>Copy code</Button></div>}
 {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}
 <div className="overflow-x-auto rounded-3xl border bg-white p-5"><h2 className="mb-4 text-xl font-semibold">Generated codes</h2><table className="w-full min-w-[600px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3">Code hint</th><th className="p-3">Months</th><th className="p-3">Used / Limit</th><th className="p-3">Expires</th><th className="p-3">Status</th><th className="p-3">Manage</th></tr></thead><tbody>{codes.map(c=><tr className="border-b" key={c.id}><td className="p-3 font-mono">{c.code_hint}</td><td className="p-3">{c.duration_months}</td><td className="p-3">{c.redemption_count} / {c.max_redemptions}</td><td className="p-3">{c.expires_at?new Date(c.expires_at).toLocaleDateString():"No expiry"}</td><td className="p-3">{c.is_active?"Active":"Disabled"}</td><td className="p-3"><Button size="sm" variant="outline" disabled={busy} onClick={()=>void toggle(c.id,!c.is_active)}>{c.is_active?"Disable":"Enable"}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>{setEditing(c.id);setEditLimit(c.max_redemptions);setEditExpiry(c.expires_at?c.expires_at.slice(0,10):"");}}>Edit limits</Button></td></tr>)}</tbody></table>{codes.length===0&&<p className="p-4 text-slate-500">No codes created yet.</p>}</div>
 {editing&&<section className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><h2 className="text-lg font-bold">Edit promotion limits</h2><p className="mt-1 text-xs text-slate-600">Changes are audited. The limit cannot be lower than existing redemptions.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Maximum redemptions<Input type="number" min={codes.find(c=>c.id===editing)?.redemption_count||1} max={100000} value={editLimit} onChange={e=>setEditLimit(Number(e.target.value))}/></label><label className="text-sm font-medium">Expiry (blank = none)<Input type="date" value={editExpiry} onChange={e=>setEditExpiry(e.target.value)}/></label></div><div className="mt-4 flex gap-2"><Button disabled={busy} onClick={()=>void saveLimits()}>Save changes</Button><Button variant="outline" disabled={busy} onClick={()=>setEditing(null)}>Cancel</Button></div></section>}
 <section className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-semibold">Recent redemptions</h2><p className="mt-1 text-xs text-slate-500">Latest 100 redemptions. Only administrators can view these records.</p>{redemptions.length===0?<p className="mt-4 text-sm text-slate-500">No codes redeemed yet.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{redemptions.map(r=><div key={r.id} className="rounded-xl border p-4"><p className="font-semibold">{r.member_name}</p><p className="text-xs text-slate-500">Code: {codes.find(c=>c.id===r.promo_code_id)?.code_hint||"Unknown"}</p><p className="mt-2 text-sm">Redeemed {new Date(r.redeemed_at).toLocaleDateString("en-GB")}</p><p className="text-sm">Trial ends {new Date(r.trial_ends_at).toLocaleDateString("en-GB")}</p></div>)}</div>}</section>
 <p className="text-sm text-amber-800">Codes can be redeemed after mobile verification. A six-month code replaces the standard three-month offer; it does not add another six months.</p>
 </div>;
}