import type { LanguageCode } from "./I18nProvider";

export const messages = {
 en: {
  nav:{home:"Home",about:"About",stories:"Success Stories",pricing:"Pricing",safety:"Safety",help:"Help",login:"Log In",signup:"Sign Up"},
  auth:{loginTitle:"Welcome back",loginDescription:"Log in to continue your CupidMatch profile.",email:"Email",password:"Password",login:"Log in",forgot:"Forgot password?",noAccount:"Don't have an account?",signup:"Sign up",signupTitle:"Create your account",signupDescription:"Join CupidMatch. You will confirm your email before publishing a profile.",fullName:"Full name",yourName:"Your name",confirmPassword:"Confirm password",create:"Create account",haveAccount:"Already have an account?",termsPrefix:"I agree to the",terms:"Terms of Service",privacy:"Privacy Policy"},
  hero:{eyebrow:"Sri Lankan matchmaking",eyebrow2:"for a brighter tomorrow",title:"Find Your",titleAccent:"Perfect Match",description:"A trusted matrimony platform for the Sri Lankan community in the UK, Canada, Australia and beyond. Real people, serious intentions, meaningful connections.",create:"Create Your Profile",explore:"Explore Matches",verified:"Verified Profiles",safe:"Safe & Secure",compatibility:"Find Compatibility"},
  pricing:{eyebrow:"CupidMatch membership",title:"Choose how you want to find your match",subtitle:"Start free. Upgrade for deeper discovery, compatibility, privacy and visibility tools.",country:"Pricing country",countryHelp:"Choose your billing country. We do not force pricing based only on your location.",popular:"Most Popular",month:"month",months3:"3 months",months6:"6 months",start:"Start free",choose:"Choose",fair:"*Unlimited interests are subject to fair-use and anti-spam controls.",hold:"Payments are currently on hold. Choosing a paid plan will not activate paid access until secure billing is enabled."}
 },
 ta: {
  nav:{home:"முகப்பு",about:"எங்களைப் பற்றி",stories:"வெற்றிக் கதைகள்",pricing:"கட்டணங்கள்",safety:"பாதுகாப்பு",help:"உதவி",login:"உள்நுழைக",signup:"பதிவு செய்க"},
  auth:{loginTitle:"மீண்டும் வரவேற்கிறோம்",loginDescription:"உங்கள் CupidMatch சுயவிவரத்தைத் தொடர உள்நுழையவும்.",email:"மின்னஞ்சல்",password:"கடவுச்சொல்",login:"உள்நுழைக",forgot:"கடவுச்சொல் மறந்துவிட்டதா?",noAccount:"கணக்கு இல்லையா?",signup:"பதிவு செய்க",signupTitle:"உங்கள் கணக்கை உருவாக்குங்கள்",signupDescription:"CupidMatch-இல் இணையுங்கள். சுயவிவரத்தை வெளியிடும் முன் உங்கள் மின்னஞ்சலை உறுதிப்படுத்த வேண்டும்.",fullName:"முழுப் பெயர்",yourName:"உங்கள் பெயர்",confirmPassword:"கடவுச்சொல்லை உறுதிப்படுத்தவும்",create:"கணக்கை உருவாக்கவும்",haveAccount:"ஏற்கனவே கணக்கு உள்ளதா?",termsPrefix:"நான் ஒப்புக்கொள்கிறேன்",terms:"சேவை விதிமுறைகள்",privacy:"தனியுரிமைக் கொள்கை"},
  hero:{eyebrow:"இலங்கையர்களுக்கான திருமணத் துணை தேடல்",eyebrow2:"ஒளிமயமான நாளைக்காக",title:"உங்கள்",titleAccent:"சரியான துணையை கண்டறியுங்கள்",description:"UK, கனடா, ஆஸ்திரேலியா மற்றும் உலகம் முழுவதும் உள்ள இலங்கை சமூகத்திற்கான நம்பகமான திருமணத் தளம். உண்மையான மனிதர்கள், தீவிரமான நோக்கங்கள், அர்த்தமுள்ள தொடர்புகள்.",create:"உங்கள் சுயவிவரத்தை உருவாக்குங்கள்",explore:"துணைகளைப் பாருங்கள்",verified:"சரிபார்க்கப்பட்ட சுயவிவரங்கள்",safe:"பாதுகாப்பானது",compatibility:"பொருத்தத்தை கண்டறியுங்கள்"},
  pricing:{eyebrow:"CupidMatch உறுப்பினர் திட்டங்கள்",title:"உங்கள் துணையைத் தேடும் முறையைத் தேர்ந்தெடுக்கவும்",subtitle:"இலவசமாக தொடங்குங்கள். மேம்பட்ட தேடல், பொருத்தம், தனியுரிமை மற்றும் தெரிவுத்திறன் வசதிகளுக்காக மேம்படுத்துங்கள்.",country:"கட்டண நாடு",countryHelp:"உங்கள் பில்லிங் நாட்டைத் தேர்ந்தெடுக்கவும். இருப்பிடத்தின் அடிப்படையில் மட்டும் கட்டணத்தை நாங்கள் கட்டாயப்படுத்த மாட்டோம்.",popular:"மிகவும் பிரபலமானது",month:"மாதம்",months3:"3 மாதங்கள்",months6:"6 மாதங்கள்",start:"இலவசமாக தொடங்குங்கள்",choose:"தேர்ந்தெடுக்கவும்",fair:"*வரம்பற்ற விருப்பங்கள் நியாயமான பயன்பாடு மற்றும் ஸ்பாம் தடுப்பு கட்டுப்பாடுகளுக்கு உட்பட்டவை.",hold:"கட்டணங்கள் தற்போது நிறுத்தப்பட்டுள்ளன. பாதுகாப்பான பில்லிங் செயல்படுத்தப்படும் வரை கட்டணத் திட்டம் செயல்படுத்தப்படாது."}
 },
 si: {
  nav:{home:"මුල් පිටුව",about:"අප ගැන",stories:"සාර්ථක කතා",pricing:"මිල ගණන්",safety:"ආරක්ෂාව",help:"උදව්",login:"පිවිසෙන්න",signup:"ලියාපදිංචි වන්න"},
  auth:{loginTitle:"නැවත සාදරයෙන් පිළිගනිමු",loginDescription:"ඔබගේ CupidMatch පැතිකඩ දිගටම කරගෙන යාමට පිවිසෙන්න.",email:"විද්‍යුත් තැපෑල",password:"මුරපදය",login:"පිවිසෙන්න",forgot:"මුරපදය අමතකද?",noAccount:"ගිණුමක් නැද්ද?",signup:"ලියාපදිංචි වන්න",signupTitle:"ඔබගේ ගිණුම සාදන්න",signupDescription:"CupidMatch සමඟ එක්වන්න. පැතිකඩ ප්‍රකාශයට පත් කිරීමට පෙර විද්‍යුත් තැපෑල තහවුරු කරන්න.",fullName:"සම්පූර්ණ නම",yourName:"ඔබගේ නම",confirmPassword:"මුරපදය තහවුරු කරන්න",create:"ගිණුම සාදන්න",haveAccount:"දැනටමත් ගිණුමක් තිබේද?",termsPrefix:"මම එකඟ වෙමි",terms:"සේවා කොන්දේසි",privacy:"පෞද්ගලිකත්ව ප්‍රතිපත්තිය"},
  hero:{eyebrow:"ශ්‍රී ලාංකික විවාහ ගැළපීම්",eyebrow2:"දීප්තිමත් හෙටක් සඳහා",title:"ඔබගේ",titleAccent:"ගැළපෙන සහකරු සොයන්න",description:"UK, කැනඩාව, ඔස්ට්‍රේලියාව සහ ලොව පුරා ශ්‍රී ලාංකික ප්‍රජාව සඳහා විශ්වාසදායක විවාහ වේදිකාවක්.",create:"ඔබගේ පැතිකඩ සාදන්න",explore:"ගැළපීම් බලන්න",verified:"තහවුරු කළ පැතිකඩ",safe:"ආරක්ෂිතයි",compatibility:"ගැළපීම සොයන්න"},
  pricing:{eyebrow:"CupidMatch සාමාජිකත්වය",title:"ඔබගේ ගැළපෙන සහකරු සොයන ආකාරය තෝරන්න",subtitle:"නොමිලේ ආරම්භ කරන්න. වැඩිදියුණු කළ සෙවීම, ගැළපීම, පෞද්ගලිකත්වය සහ දෘශ්‍යතාව සඳහා උසස් කරන්න.",country:"මිල නියම කරන රට",countryHelp:"ඔබගේ බිල්පත් රට තෝරන්න. ස්ථානය මත පමණක් මිල බලහත්කාරයෙන් තීරණය නොකරමු.",popular:"වඩාත් ජනප්‍රිය",month:"මාසය",months3:"මාස 3",months6:"මාස 6",start:"නොමිලේ ආරම්භ කරන්න",choose:"තෝරන්න",fair:"*අසීමිත කැමැත්ත සාධාරණ භාවිත සහ ස්පෑම්-විරෝධී පාලනයන්ට යටත් වේ.",hold:"ගෙවීම් දැනට අත්හිටුවා ඇත. ආරක්ෂිත බිල්පත් ක්‍රමය සක්‍රීය වන තුරු ගෙවන සැලැස්මක් සක්‍රීය නොවේ."}
 },
 fr: {
  nav:{home:"Accueil",about:"À propos",stories:"Témoignages",pricing:"Tarifs",safety:"Sécurité",help:"Aide",login:"Connexion",signup:"S'inscrire"},
  auth:{loginTitle:"Bon retour",loginDescription:"Connectez-vous pour continuer votre profil CupidMatch.",email:"E-mail",password:"Mot de passe",login:"Connexion",forgot:"Mot de passe oublié ?",noAccount:"Vous n'avez pas de compte ?",signup:"S'inscrire",signupTitle:"Créez votre compte",signupDescription:"Rejoignez CupidMatch. Vous confirmerez votre e-mail avant de publier votre profil.",fullName:"Nom complet",yourName:"Votre nom",confirmPassword:"Confirmer le mot de passe",create:"Créer un compte",haveAccount:"Vous avez déjà un compte ?",termsPrefix:"J'accepte les",terms:"Conditions d'utilisation",privacy:"Politique de confidentialité"},
  hero:{eyebrow:"Rencontres matrimoniales sri-lankaises",eyebrow2:"pour un avenir plus lumineux",title:"Trouvez votre",titleAccent:"partenaire idéal",description:"Une plateforme matrimoniale de confiance pour la communauté sri-lankaise au Royaume-Uni, au Canada, en Australie et ailleurs.",create:"Créer votre profil",explore:"Découvrir les profils",verified:"Profils vérifiés",safe:"Sûr et sécurisé",compatibility:"Trouver la compatibilité"},
  pricing:{eyebrow:"Abonnement CupidMatch",title:"Choisissez comment vous souhaitez trouver votre partenaire",subtitle:"Commencez gratuitement. Passez à une offre supérieure pour profiter d'outils avancés de découverte, compatibilité, confidentialité et visibilité.",country:"Pays de facturation",countryHelp:"Choisissez votre pays de facturation. Nous n'imposons pas un tarif uniquement selon votre localisation.",popular:"Le plus populaire",month:"mois",months3:"3 mois",months6:"6 mois",start:"Commencer gratuitement",choose:"Choisir",fair:"*Les intérêts illimités sont soumis à des règles d'utilisation équitable et anti-spam.",hold:"Les paiements sont actuellement suspendus. Aucun abonnement payant ne sera activé avant la mise en service de la facturation sécurisée."}
 },
 nl: {
  nav:{home:"Home",about:"Over ons",stories:"Succesverhalen",pricing:"Prijzen",safety:"Veiligheid",help:"Help",login:"Inloggen",signup:"Registreren"},
  auth:{loginTitle:"Welkom terug",loginDescription:"Log in om verder te gaan met je CupidMatch-profiel.",email:"E-mail",password:"Wachtwoord",login:"Inloggen",forgot:"Wachtwoord vergeten?",noAccount:"Nog geen account?",signup:"Registreren",signupTitle:"Maak je account",signupDescription:"Word lid van CupidMatch. Bevestig je e-mail voordat je een profiel publiceert.",fullName:"Volledige naam",yourName:"Je naam",confirmPassword:"Bevestig wachtwoord",create:"Account maken",haveAccount:"Heb je al een account?",termsPrefix:"Ik ga akkoord met de",terms:"Servicevoorwaarden",privacy:"Privacybeleid"},
  hero:{eyebrow:"Sri Lankaanse matchmaking",eyebrow2:"voor een mooiere toekomst",title:"Vind jouw",titleAccent:"perfecte match",description:"Een betrouwbaar matrimonyplatform voor de Sri Lankaanse gemeenschap in het VK, Canada, Australië en daarbuiten.",create:"Maak je profiel",explore:"Bekijk matches",verified:"Geverifieerde profielen",safe:"Veilig en betrouwbaar",compatibility:"Vind compatibiliteit"},
  pricing:{eyebrow:"CupidMatch-lidmaatschap",title:"Kies hoe je jouw match wilt vinden",subtitle:"Begin gratis. Upgrade voor uitgebreidere zoek-, compatibiliteits-, privacy- en zichtbaarheidsfuncties.",country:"Factureringsland",countryHelp:"Kies je factureringsland. We leggen geen prijs op uitsluitend op basis van je locatie.",popular:"Meest populair",month:"maand",months3:"3 maanden",months6:"6 maanden",start:"Gratis beginnen",choose:"Kiezen",fair:"*Onbeperkte interesses vallen onder fair-use- en antispamregels.",hold:"Betalingen zijn momenteel gepauzeerd. Een betaald abonnement wordt pas geactiveerd zodra veilige facturering beschikbaar is."}
 }
} as const;
export function getMessages(language:LanguageCode){return messages[language] ?? messages.en;}
