import type { LanguageCode } from "./I18nProvider";

export const messages = {
 en: {
  nav:{home:"Home",about:"About",stories:"Success Stories",pricing:"Pricing",safety:"Safety",help:"Help",login:"Log In",signup:"Sign Up"},
  auth:{loginTitle:"Welcome back",loginDescription:"Log in to continue your CupidMatch profile.",email:"Email",password:"Password",login:"Log in",forgot:"Forgot password?",noAccount:"Don't have an account?",signup:"Sign up",signupTitle:"Create your account",signupDescription:"Join CupidMatch. You will confirm your email before publishing a profile.",fullName:"Full name",yourName:"Your name",confirmPassword:"Confirm password",create:"Create account",haveAccount:"Already have an account?",termsPrefix:"I agree to the",terms:"Terms of Service",privacy:"Privacy Policy"},
  hero:{eyebrow:"Sri Lankan matchmaking",eyebrow2:"for a brighter tomorrow",title:"Find Your",titleAccent:"Perfect Match",description:"A trusted matrimony platform for the Sri Lankan community in the UK, Canada, Australia and beyond. Real people, serious intentions, meaningful connections.",create:"Create Your Profile",explore:"Explore Matches",verified:"Verified Profiles",safe:"Safe & Secure",compatibility:"Find Compatibility"},
  onboarding:{step:"Step",of:"of",saving:"Saving…",saved:"Saved",failed:"Save failed",draft:"Draft",displayName:"Display name",dob:"Date of birth (kept private)",dobHelp:"We only show a derived age after you publish. Your date of birth is never shown on discovery.",profession:"Profession (optional)",adult:"I confirm I am 18 or older and eligible to use CupidMatch.",country:"Country",selectCountry:"Select country",region:"City or region (not a street address)",languages:"Languages",looking:"What are you looking for?",timeline:"Timeline",introduction:"Introduction",education:"Education",smoking:"Smoking",drinking:"Drinking",hobbies:"Hobbies and interests",back:"Back",continue:"Continue",saveExit:"Save and exit",publish:"Publish profile",review:"Please check this step",notAdded:"Not added yet",cultureHelp:"This step is optional. Skip it if you would rather discuss culture later.",religion:"Religion or worldview (optional)",culture:"Cultural background (optional)",familyInvolvement:"Family involvement preference (optional)",traditions:"Festivals and traditions that matter (optional)",skipCulture:"Skip cultural preferences",relocation:"Relocation",futureCountries:"Preferred future countries (optional)",longDistance:"Long-distance comfort (optional)",familyResponsibilities:"Family responsibilities to consider (optional)",profilePhoto:"Profile photo (optional until you are ready)",additionalPhotos:"Additional photos (optional)",photoPrivacy:"Photo privacy",uploading:"Uploading…",name:"Name",location:"Location",reviewDob:"Date of birth stays private. We will only show a derived age after you publish.",publishConfirm:"I confirm these details are accurate and I want to publish my profile for other members to see."},
  pricing:{eyebrow:"CupidMatch membership",title:"Choose how you want to find your match",subtitle:"Start free. Upgrade for deeper discovery, compatibility, privacy and visibility tools.",country:"Pricing country",countryHelp:"Choose your billing country. We do not force pricing based only on your location.",popular:"Most Popular",month:"month",months3:"3 months",months6:"6 months",start:"Start free",choose:"Choose",fair:"*Unlimited interests are subject to fair-use and anti-spam controls.",hold:"Payments are currently on hold. Choosing a paid plan will not activate paid access until secure billing is enabled."}
 },
 ta: {
  nav:{home:"முகப்பு",about:"எங்களைப் பற்றி",stories:"வெற்றிக் கதைகள்",pricing:"கட்டணங்கள்",safety:"பாதுகாப்பு",help:"உதவி",login:"உள்நுழைக",signup:"பதிவு செய்க"},
  auth:{loginTitle:"மீண்டும் வரவேற்கிறோம்",loginDescription:"உங்கள் CupidMatch சுயவிவரத்தைத் தொடர உள்நுழையவும்.",email:"மின்னஞ்சல்",password:"கடவுச்சொல்",login:"உள்நுழைக",forgot:"கடவுச்சொல் மறந்துவிட்டதா?",noAccount:"கணக்கு இல்லையா?",signup:"பதிவு செய்க",signupTitle:"உங்கள் கணக்கை உருவாக்குங்கள்",signupDescription:"CupidMatch-இல் இணையுங்கள். சுயவிவரத்தை வெளியிடும் முன் உங்கள் மின்னஞ்சலை உறுதிப்படுத்த வேண்டும்.",fullName:"முழுப் பெயர்",yourName:"உங்கள் பெயர்",confirmPassword:"கடவுச்சொல்லை உறுதிப்படுத்தவும்",create:"கணக்கை உருவாக்கவும்",haveAccount:"ஏற்கனவே கணக்கு உள்ளதா?",termsPrefix:"நான் ஒப்புக்கொள்கிறேன்",terms:"சேவை விதிமுறைகள்",privacy:"தனியுரிமைக் கொள்கை"},
  hero:{eyebrow:"இலங்கையர்களுக்கான திருமணத் துணை தேடல்",eyebrow2:"ஒளிமயமான நாளைக்காக",title:"உங்கள்",titleAccent:"சரியான துணையை கண்டறியுங்கள்",description:"UK, கனடா, ஆஸ்திரேலியா மற்றும் உலகம் முழுவதும் உள்ள இலங்கை சமூகத்திற்கான நம்பகமான திருமணத் தளம். உண்மையான மனிதர்கள், தீவிரமான நோக்கங்கள், அர்த்தமுள்ள தொடர்புகள்.",create:"உங்கள் சுயவிவரத்தை உருவாக்குங்கள்",explore:"துணைகளைப் பாருங்கள்",verified:"சரிபார்க்கப்பட்ட சுயவிவரங்கள்",safe:"பாதுகாப்பானது",compatibility:"பொருத்தத்தை கண்டறியுங்கள்"},
  onboarding:{step:"படி",of:"இல்",saving:"சேமிக்கிறது…",saved:"சேமிக்கப்பட்டது",failed:"சேமிக்க முடியவில்லை",draft:"வரைவு",displayName:"காண்பிக்கும் பெயர்",dob:"பிறந்த தேதி (தனிப்பட்டது)",dobHelp:"வெளியிட்ட பிறகு வயது மட்டும் காட்டப்படும். பிறந்த தேதி தேடலில் காட்டப்படாது.",profession:"தொழில் (விருப்பம்)",adult:"நான் 18 வயது அல்லது அதற்கு மேற்பட்டவர் என்றும் CupidMatch பயன்படுத்த தகுதியானவர் என்றும் உறுதிப்படுத்துகிறேன்.",country:"நாடு",selectCountry:"நாட்டைத் தேர்ந்தெடுக்கவும்",region:"நகரம் அல்லது பகுதி (தெரு முகவரி அல்ல)",languages:"மொழிகள்",looking:"நீங்கள் எதைத் தேடுகிறீர்கள்?",timeline:"காலவரை",introduction:"அறிமுகம்",education:"கல்வி",smoking:"புகைப்பழக்கம்",drinking:"மது அருந்துதல்",hobbies:"பொழுதுபோக்குகள் மற்றும் விருப்பங்கள்",back:"பின்செல்",continue:"தொடரவும்",saveExit:"சேமித்து வெளியேறு",publish:"சுயவிவரத்தை வெளியிடு",review:"இந்த படியை சரிபார்க்கவும்",notAdded:"இன்னும் சேர்க்கப்படவில்லை",cultureHelp:"இந்த படி விருப்பமானது. கலாச்சாரத்தை பின்னர் பேச விரும்பினால் தவிர்க்கலாம்.",religion:"மதம் அல்லது உலகக் கண்ணோட்டம் (விருப்பம்)",culture:"கலாச்சார பின்னணி (விருப்பம்)",familyInvolvement:"குடும்ப ஈடுபாட்டு விருப்பம் (விருப்பம்)",traditions:"முக்கியமான விழாக்கள் மற்றும் மரபுகள் (விருப்பம்)",skipCulture:"கலாச்சார விருப்பங்களைத் தவிர்க்கவும்",relocation:"இடமாற்றம்",futureCountries:"எதிர்காலத்தில் விரும்பும் நாடுகள் (விருப்பம்)",longDistance:"தொலைதூர உறவு வசதி (விருப்பம்)",familyResponsibilities:"கருத்தில் கொள்ள வேண்டிய குடும்ப பொறுப்புகள் (விருப்பம்)",profilePhoto:"சுயவிவரப் படம் (தயாராகும் வரை விருப்பம்)",additionalPhotos:"கூடுதல் புகைப்படங்கள் (விருப்பம்)",photoPrivacy:"புகைப்பட தனியுரிமை",uploading:"பதிவேற்றுகிறது…",name:"பெயர்",location:"இருப்பிடம்",reviewDob:"பிறந்த தேதி தனிப்பட்டதாக இருக்கும். வெளியிட்ட பின் வயது மட்டும் காட்டப்படும்.",publishConfirm:"இந்த விவரங்கள் சரியானவை என்றும் மற்ற உறுப்பினர்கள் பார்க்க என் சுயவிவரத்தை வெளியிட விரும்புகிறேன் என்றும் உறுதிப்படுத்துகிறேன்."},
  pricing:{eyebrow:"CupidMatch உறுப்பினர் திட்டங்கள்",title:"உங்கள் துணையைத் தேடும் முறையைத் தேர்ந்தெடுக்கவும்",subtitle:"இலவசமாக தொடங்குங்கள். மேம்பட்ட தேடல், பொருத்தம், தனியுரிமை மற்றும் தெரிவுத்திறன் வசதிகளுக்காக மேம்படுத்துங்கள்.",country:"கட்டண நாடு",countryHelp:"உங்கள் பில்லிங் நாட்டைத் தேர்ந்தெடுக்கவும். இருப்பிடத்தின் அடிப்படையில் மட்டும் கட்டணத்தை நாங்கள் கட்டாயப்படுத்த மாட்டோம்.",popular:"மிகவும் பிரபலமானது",month:"மாதம்",months3:"3 மாதங்கள்",months6:"6 மாதங்கள்",start:"இலவசமாக தொடங்குங்கள்",choose:"தேர்ந்தெடுக்கவும்",fair:"*வரம்பற்ற விருப்பங்கள் நியாயமான பயன்பாடு மற்றும் ஸ்பாம் தடுப்பு கட்டுப்பாடுகளுக்கு உட்பட்டவை.",hold:"கட்டணங்கள் தற்போது நிறுத்தப்பட்டுள்ளன. பாதுகாப்பான பில்லிங் செயல்படுத்தப்படும் வரை கட்டணத் திட்டம் செயல்படுத்தப்படாது."}
 },
 si: {
  nav:{home:"මුල් පිටුව",about:"අප ගැන",stories:"සාර්ථක කතා",pricing:"මිල ගණන්",safety:"ආරක්ෂාව",help:"උදව්",login:"පිවිසෙන්න",signup:"ලියාපදිංචි වන්න"},
  auth:{loginTitle:"නැවත සාදරයෙන් පිළිගනිමු",loginDescription:"ඔබගේ CupidMatch පැතිකඩ දිගටම කරගෙන යාමට පිවිසෙන්න.",email:"විද්‍යුත් තැපෑල",password:"මුරපදය",login:"පිවිසෙන්න",forgot:"මුරපදය අමතකද?",noAccount:"ගිණුමක් නැද්ද?",signup:"ලියාපදිංචි වන්න",signupTitle:"ඔබගේ ගිණුම සාදන්න",signupDescription:"CupidMatch සමඟ එක්වන්න. පැතිකඩ ප්‍රකාශයට පත් කිරීමට පෙර විද්‍යුත් තැපෑල තහවුරු කරන්න.",fullName:"සම්පූර්ණ නම",yourName:"ඔබගේ නම",confirmPassword:"මුරපදය තහවුරු කරන්න",create:"ගිණුම සාදන්න",haveAccount:"දැනටමත් ගිණුමක් තිබේද?",termsPrefix:"මම එකඟ වෙමි",terms:"සේවා කොන්දේසි",privacy:"පෞද්ගලිකත්ව ප්‍රතිපත්තිය"},
  hero:{eyebrow:"ශ්‍රී ලාංකික විවාහ ගැළපීම්",eyebrow2:"දීප්තිමත් හෙටක් සඳහා",title:"ඔබගේ",titleAccent:"ගැළපෙන සහකරු සොයන්න",description:"UK, කැනඩාව, ඔස්ට්‍රේලියාව සහ ලොව පුරා ශ්‍රී ලාංකික ප්‍රජාව සඳහා විශ්වාසදායක විවාහ වේදිකාවක්.",create:"ඔබගේ පැතිකඩ සාදන්න",explore:"ගැළපීම් බලන්න",verified:"තහවුරු කළ පැතිකඩ",safe:"ආරක්ෂිතයි",compatibility:"ගැළපීම සොයන්න"},
  onboarding:{step:"පියවර",of:"න්",saving:"සුරකිමින්…",saved:"සුරකින ලදී",failed:"සුරැකීම අසාර්ථකයි",draft:"කෙටුම්පත",displayName:"පෙන්වන නම",dob:"උපන් දිනය (පෞද්ගලිකයි)",dobHelp:"ප්‍රකාශයට පත් කළ පසු වයස පමණක් පෙන්වයි. උපන් දිනය සෙවුමේ නොපෙන්වයි.",profession:"වෘත්තිය (විකල්ප)",adult:"මට වයස 18 හෝ ඊට වැඩි බවත් CupidMatch භාවිතයට සුදුසු බවත් තහවුරු කරමි.",country:"රට",selectCountry:"රට තෝරන්න",region:"නගරය හෝ ප්‍රදේශය (වීදි ලිපිනයක් නොවේ)",languages:"භාෂා",looking:"ඔබ සොයන්නේ කුමක්ද?",timeline:"කාලසීමාව",introduction:"හැඳින්වීම",education:"අධ්‍යාපනය",smoking:"දුම්පානය",drinking:"මත්පැන්",hobbies:"විනෝදාංශ සහ රුචිකත්වයන්",back:"ආපසු",continue:"ඉදිරියට",saveExit:"සුරකින්න සහ පිටවන්න",publish:"පැතිකඩ ප්‍රකාශයට පත් කරන්න",review:"මෙම පියවර පරීක්ෂා කරන්න",notAdded:"තවම එකතු කර නැත",cultureHelp:"මෙම පියවර විකල්පයි. සංස්කෘතිය පසුව සාකච්ඡා කිරීමට කැමති නම් මඟ හරින්න.",religion:"ආගම හෝ ලෝක දෘෂ්ටිය (විකල්ප)",culture:"සංස්කෘතික පසුබිම (විකල්ප)",familyInvolvement:"පවුලේ සහභාගීත්ව මනාපය (විකල්ප)",traditions:"වැදගත් උත්සව සහ සම්ප්‍රදායන් (විකල්ප)",skipCulture:"සංස්කෘතික මනාප මඟ හරින්න",relocation:"ස්ථාන මාරුව",futureCountries:"අනාගතයේ කැමති රටවල් (විකල්ප)",longDistance:"දුරස්ථ සම්බන්ධතා පහසුව (විකල්ප)",familyResponsibilities:"සලකා බැලිය යුතු පවුල් වගකීම් (විකල්ප)",profilePhoto:"පැතිකඩ ඡායාරූපය (විකල්ප)",additionalPhotos:"අමතර ඡායාරූප (විකල්ප)",photoPrivacy:"ඡායාරූප පෞද්ගලිකත්වය",uploading:"උඩුගත කරමින්…",name:"නම",location:"ස්ථානය",reviewDob:"උපන් දිනය පෞද්ගලිකව තබා ගනී. ප්‍රකාශයට පත් කළ පසු වයස පමණක් පෙන්වයි.",publishConfirm:"මෙම විස්තර නිවැරදි බවත් අනෙකුත් සාමාජිකයින්ට පෙනෙන ලෙස මගේ පැතිකඩ ප්‍රකාශයට පත් කිරීමට අවශ්‍ය බවත් තහවුරු කරමි."},
  pricing:{eyebrow:"CupidMatch සාමාජිකත්වය",title:"ඔබගේ ගැළපෙන සහකරු සොයන ආකාරය තෝරන්න",subtitle:"නොමිලේ ආරම්භ කරන්න. වැඩිදියුණු කළ සෙවීම, ගැළපීම, පෞද්ගලිකත්වය සහ දෘශ්‍යතාව සඳහා උසස් කරන්න.",country:"මිල නියම කරන රට",countryHelp:"ඔබගේ බිල්පත් රට තෝරන්න. ස්ථානය මත පමණක් මිල බලහත්කාරයෙන් තීරණය නොකරමු.",popular:"වඩාත් ජනප්‍රිය",month:"මාසය",months3:"මාස 3",months6:"මාස 6",start:"නොමිලේ ආරම්භ කරන්න",choose:"තෝරන්න",fair:"*අසීමිත කැමැත්ත සාධාරණ භාවිත සහ ස්පෑම්-විරෝධී පාලනයන්ට යටත් වේ.",hold:"ගෙවීම් දැනට අත්හිටුවා ඇත. ආරක්ෂිත බිල්පත් ක්‍රමය සක්‍රීය වන තුරු ගෙවන සැලැස්මක් සක්‍රීය නොවේ."}
 },
 fr: {
  nav:{home:"Accueil",about:"À propos",stories:"Témoignages",pricing:"Tarifs",safety:"Sécurité",help:"Aide",login:"Connexion",signup:"S'inscrire"},
  auth:{loginTitle:"Bon retour",loginDescription:"Connectez-vous pour continuer votre profil CupidMatch.",email:"E-mail",password:"Mot de passe",login:"Connexion",forgot:"Mot de passe oublié ?",noAccount:"Vous n'avez pas de compte ?",signup:"S'inscrire",signupTitle:"Créez votre compte",signupDescription:"Rejoignez CupidMatch. Vous confirmerez votre e-mail avant de publier votre profil.",fullName:"Nom complet",yourName:"Votre nom",confirmPassword:"Confirmer le mot de passe",create:"Créer un compte",haveAccount:"Vous avez déjà un compte ?",termsPrefix:"J'accepte les",terms:"Conditions d'utilisation",privacy:"Politique de confidentialité"},
  hero:{eyebrow:"Rencontres matrimoniales sri-lankaises",eyebrow2:"pour un avenir plus lumineux",title:"Trouvez votre",titleAccent:"partenaire idéal",description:"Une plateforme matrimoniale de confiance pour la communauté sri-lankaise au Royaume-Uni, au Canada, en Australie et ailleurs.",create:"Créer votre profil",explore:"Découvrir les profils",verified:"Profils vérifiés",safe:"Sûr et sécurisé",compatibility:"Trouver la compatibilité"},
  onboarding:{step:"Étape",of:"sur",saving:"Enregistrement…",saved:"Enregistré",failed:"Échec de l'enregistrement",draft:"Brouillon",displayName:"Nom affiché",dob:"Date de naissance (privée)",dobHelp:"Après publication, seul votre âge calculé est affiché. Votre date de naissance n'apparaît jamais dans la découverte.",profession:"Profession (facultatif)",adult:"Je confirme avoir 18 ans ou plus et être autorisé à utiliser CupidMatch.",country:"Pays",selectCountry:"Sélectionner un pays",region:"Ville ou région (pas une adresse)",languages:"Langues",looking:"Que recherchez-vous ?",timeline:"Calendrier",introduction:"Présentation",education:"Études",smoking:"Tabac",drinking:"Alcool",hobbies:"Loisirs et centres d'intérêt",back:"Retour",continue:"Continuer",saveExit:"Enregistrer et quitter",publish:"Publier le profil",review:"Vérifiez cette étape",notAdded:"Pas encore renseigné",cultureHelp:"Cette étape est facultative. Passez-la si vous préférez parler de culture plus tard.",religion:"Religion ou vision du monde (facultatif)",culture:"Origine culturelle (facultatif)",familyInvolvement:"Préférence d’implication familiale (facultatif)",traditions:"Fêtes et traditions importantes (facultatif)",skipCulture:"Passer les préférences culturelles",relocation:"Déménagement",futureCountries:"Pays souhaités à l’avenir (facultatif)",longDistance:"Aisance avec la distance (facultatif)",familyResponsibilities:"Responsabilités familiales à considérer (facultatif)",profilePhoto:"Photo de profil (facultative)",additionalPhotos:"Photos supplémentaires (facultatif)",photoPrivacy:"Confidentialité des photos",uploading:"Téléversement…",name:"Nom",location:"Lieu",reviewDob:"Votre date de naissance reste privée. Seul votre âge calculé sera affiché après publication.",publishConfirm:"Je confirme que ces informations sont exactes et souhaite publier mon profil afin que les autres membres puissent le voir."},
  pricing:{eyebrow:"Abonnement CupidMatch",title:"Choisissez comment vous souhaitez trouver votre partenaire",subtitle:"Commencez gratuitement. Passez à une offre supérieure pour profiter d'outils avancés de découverte, compatibilité, confidentialité et visibilité.",country:"Pays de facturation",countryHelp:"Choisissez votre pays de facturation. Nous n'imposons pas un tarif uniquement selon votre localisation.",popular:"Le plus populaire",month:"mois",months3:"3 mois",months6:"6 mois",start:"Commencer gratuitement",choose:"Choisir",fair:"*Les intérêts illimités sont soumis à des règles d'utilisation équitable et anti-spam.",hold:"Les paiements sont actuellement suspendus. Aucun abonnement payant ne sera activé avant la mise en service de la facturation sécurisée."}
 },
 nl: {
  nav:{home:"Home",about:"Over ons",stories:"Succesverhalen",pricing:"Prijzen",safety:"Veiligheid",help:"Help",login:"Inloggen",signup:"Registreren"},
  auth:{loginTitle:"Welkom terug",loginDescription:"Log in om verder te gaan met je CupidMatch-profiel.",email:"E-mail",password:"Wachtwoord",login:"Inloggen",forgot:"Wachtwoord vergeten?",noAccount:"Nog geen account?",signup:"Registreren",signupTitle:"Maak je account",signupDescription:"Word lid van CupidMatch. Bevestig je e-mail voordat je een profiel publiceert.",fullName:"Volledige naam",yourName:"Je naam",confirmPassword:"Bevestig wachtwoord",create:"Account maken",haveAccount:"Heb je al een account?",termsPrefix:"Ik ga akkoord met de",terms:"Servicevoorwaarden",privacy:"Privacybeleid"},
  hero:{eyebrow:"Sri Lankaanse matchmaking",eyebrow2:"voor een mooiere toekomst",title:"Vind jouw",titleAccent:"perfecte match",description:"Een betrouwbaar matrimonyplatform voor de Sri Lankaanse gemeenschap in het VK, Canada, Australië en daarbuiten.",create:"Maak je profiel",explore:"Bekijk matches",verified:"Geverifieerde profielen",safe:"Veilig en betrouwbaar",compatibility:"Vind compatibiliteit"},
  onboarding:{step:"Stap",of:"van",saving:"Opslaan…",saved:"Opgeslagen",failed:"Opslaan mislukt",draft:"Concept",displayName:"Weergavenaam",dob:"Geboortedatum (privé)",dobHelp:"Na publicatie tonen we alleen je berekende leeftijd. Je geboortedatum wordt nooit in ontdekken getoond.",profession:"Beroep (optioneel)",adult:"Ik bevestig dat ik 18 jaar of ouder ben en CupidMatch mag gebruiken.",country:"Land",selectCountry:"Selecteer land",region:"Stad of regio (geen straatadres)",languages:"Talen",looking:"Waar ben je naar op zoek?",timeline:"Tijdlijn",introduction:"Introductie",education:"Opleiding",smoking:"Roken",drinking:"Alcohol",hobbies:"Hobby's en interesses",back:"Terug",continue:"Doorgaan",saveExit:"Opslaan en afsluiten",publish:"Profiel publiceren",review:"Controleer deze stap",notAdded:"Nog niet toegevoegd",cultureHelp:"Deze stap is optioneel. Sla hem over als je cultuur liever later bespreekt.",religion:"Religie of levensbeschouwing (optioneel)",culture:"Culturele achtergrond (optioneel)",familyInvolvement:"Voorkeur voor familiebetrokkenheid (optioneel)",traditions:"Belangrijke feesten en tradities (optioneel)",skipCulture:"Culturele voorkeuren overslaan",relocation:"Verhuizen",futureCountries:"Gewenste toekomstige landen (optioneel)",longDistance:"Comfort met lange afstand (optioneel)",familyResponsibilities:"Familieverantwoordelijkheden om rekening mee te houden (optioneel)",profilePhoto:"Profielfoto (optioneel)",additionalPhotos:"Extra foto’s (optioneel)",photoPrivacy:"Fotoprivacy",uploading:"Uploaden…",name:"Naam",location:"Locatie",reviewDob:"Je geboortedatum blijft privé. Na publicatie tonen we alleen je berekende leeftijd.",publishConfirm:"Ik bevestig dat deze gegevens juist zijn en wil mijn profiel publiceren zodat andere leden het kunnen zien."},
  pricing:{eyebrow:"CupidMatch-lidmaatschap",title:"Kies hoe je jouw match wilt vinden",subtitle:"Begin gratis. Upgrade voor uitgebreidere zoek-, compatibiliteits-, privacy- en zichtbaarheidsfuncties.",country:"Factureringsland",countryHelp:"Kies je factureringsland. We leggen geen prijs op uitsluitend op basis van je locatie.",popular:"Meest populair",month:"maand",months3:"3 maanden",months6:"6 maanden",start:"Gratis beginnen",choose:"Kiezen",fair:"*Onbeperkte interesses vallen onder fair-use- en antispamregels.",hold:"Betalingen zijn momenteel gepauzeerd. Een betaald abonnement wordt pas geactiveerd zodra veilige facturering beschikbaar is."}
 }
} as const;
export function getMessages(language:LanguageCode){return messages[language] ?? messages.en;}
