import type { BiodataTemplateDef } from "./types";

export const TEMPLATE_VERSION = 1;

export const TEMPLATES: BiodataTemplateDef[] = [
  {
    id: "ganesha-ivory",
    version: TEMPLATE_VERSION,
    name: "Ganesha Ivory",
    description: "Warm ivory page with optional Ganesha line art and bronze accents.",
    categories: ["religious-cultural"],
    layout: "classic-two-col",
    decoration: "ganesha",
    defaultPalette: {
      bg: "#FBF6EE",
      ink: "#2C2416",
      accent: "#A67C52",
      muted: "#8A7A64",
      border: "#D4C4A8",
    },
    fonts: { heading: "Cormorant Garamond", body: "Inter" },
    supportsReligiousArt: true,
    religiousMotif: "ganesha",
    defaultDesign: {
      photoPosition: "right",
      photoShape: "rounded",
      showReligiousArt: false,
      borderIntensity: 0.7,
      artworkIntensity: 0.55,
    },
  },
  {
    id: "temple-lotus",
    version: TEMPLATE_VERSION,
    name: "Temple Lotus",
    description: "Lotus border composition with deep burgundy and temple-inspired framing.",
    categories: ["religious-cultural"],
    layout: "heritage",
    decoration: "lotus",
    defaultPalette: {
      bg: "#FFF8F6",
      ink: "#3B1520",
      accent: "#8B1E3F",
      muted: "#8F6B74",
      border: "#E2B8C2",
    },
    fonts: { heading: "Playfair Display", body: "Source Sans 3" },
    supportsReligiousArt: true,
    religiousMotif: "lotus",
    defaultDesign: {
      photoPosition: "left",
      photoShape: "circle",
      showReligiousArt: false,
      borderIntensity: 0.85,
      artworkIntensity: 0.65,
    },
  },
  {
    id: "buddhist-serenity",
    version: TEMPLATE_VERSION,
    name: "Buddhist Serenity",
    description: "Restrained lotus artwork on warm cream with calm, centred typography.",
    categories: ["religious-cultural", "minimal"],
    layout: "serene",
    decoration: "lotus",
    defaultPalette: {
      bg: "#FAF6F0",
      ink: "#2F2A24",
      accent: "#8C7355",
      muted: "#7A7268",
      border: "#E0D5C6",
    },
    fonts: { heading: "Lora", body: "Nunito Sans" },
    supportsReligiousArt: true,
    religiousMotif: "lotus",
    defaultDesign: {
      photoPosition: "top",
      photoShape: "circle",
      showReligiousArt: false,
      borderIntensity: 0.4,
      artworkIntensity: 0.35,
      spacing: 1.15,
    },
  },
  {
    id: "bodhi-elegance",
    version: TEMPLATE_VERSION,
    name: "Bodhi Elegance",
    description: "Bodhi-leaf corner motifs with sage green and soft botanical balance.",
    categories: ["religious-cultural"],
    layout: "garden",
    decoration: "bodhi",
    defaultPalette: {
      bg: "#F7FAF6",
      ink: "#243028",
      accent: "#5F7A5A",
      muted: "#6E7A6C",
      border: "#C9D6C4",
    },
    fonts: { heading: "EB Garamond", body: "Karla" },
    supportsReligiousArt: true,
    religiousMotif: "bodhi",
    defaultDesign: {
      photoPosition: "right",
      photoShape: "rounded",
      showReligiousArt: false,
      borderIntensity: 0.55,
      artworkIntensity: 0.6,
    },
  },
  {
    id: "christian-grace",
    version: TEMPLATE_VERSION,
    name: "Christian Grace",
    description: "Clean navy typography with optional small cross and formal structure.",
    categories: ["religious-cultural", "minimal"],
    layout: "centered-formal",
    decoration: "cross",
    defaultPalette: {
      bg: "#F8FAFC",
      ink: "#1B2A41",
      accent: "#2E4A6F",
      muted: "#5C6B7A",
      border: "#C5D0DC",
    },
    fonts: { heading: "Libre Baskerville", body: "Open Sans" },
    supportsReligiousArt: true,
    religiousMotif: "cross",
    defaultDesign: {
      photoPosition: "top",
      photoShape: "square",
      showReligiousArt: false,
      borderIntensity: 0.45,
      artworkIntensity: 0.3,
    },
  },
  {
    id: "chapel-florals",
    version: TEMPLATE_VERSION,
    name: "Chapel Florals",
    description: "Delicate floral frame with soft blush tones and optional cross motif.",
    categories: ["religious-cultural", "seasonal"],
    layout: "garden",
    decoration: "floral",
    defaultPalette: {
      bg: "#FFF9F8",
      ink: "#3A2A32",
      accent: "#B76E79",
      muted: "#8A6F78",
      border: "#E8C9CF",
    },
    fonts: { heading: "Cormorant Garamond", body: "Quicksand" },
    supportsReligiousArt: true,
    religiousMotif: "cross",
    defaultDesign: {
      photoPosition: "left",
      photoShape: "rounded",
      showReligiousArt: false,
      borderIntensity: 0.75,
      artworkIntensity: 0.7,
    },
  },
  {
    id: "islamic-geometry",
    version: TEMPLATE_VERSION,
    name: "Islamic Geometry",
    description: "Emerald geometric border with optional crescent and precise columns.",
    categories: ["religious-cultural", "modern"],
    layout: "geometric",
    decoration: "geometric",
    defaultPalette: {
      bg: "#F4FAF7",
      ink: "#14352C",
      accent: "#0F7A5A",
      muted: "#4F6F64",
      border: "#A8D0C0",
    },
    fonts: { heading: "Amiri", body: "Inter" },
    supportsReligiousArt: true,
    religiousMotif: "crescent",
    defaultDesign: {
      photoPosition: "right",
      photoShape: "square",
      showReligiousArt: false,
      borderIntensity: 0.9,
      artworkIntensity: 0.55,
    },
  },
  {
    id: "crescent-pearl",
    version: TEMPLATE_VERSION,
    name: "Crescent Pearl",
    description: "Pearl background with refined geometric arch and soft silver accents.",
    categories: ["religious-cultural", "minimal"],
    layout: "centered-formal",
    decoration: "crescent",
    defaultPalette: {
      bg: "#F7F8FA",
      ink: "#2A3038",
      accent: "#6B7C8F",
      muted: "#7A8490",
      border: "#D0D6DE",
    },
    fonts: { heading: "Cinzel", body: "Lato" },
    supportsReligiousArt: true,
    religiousMotif: "crescent",
    defaultDesign: {
      photoPosition: "top",
      photoShape: "circle",
      showReligiousArt: false,
      borderIntensity: 0.5,
      artworkIntensity: 0.4,
    },
  },
  {
    id: "sri-lankan-heritage",
    version: TEMPLATE_VERSION,
    name: "Sri Lankan Heritage",
    description: "Original textile-inspired border with warm terracotta and heritage layout.",
    categories: ["religious-cultural", "photo"],
    layout: "heritage",
    decoration: "textile",
    defaultPalette: {
      bg: "#FFF7F1",
      ink: "#3A2418",
      accent: "#C45C26",
      muted: "#8A6A55",
      border: "#E2C2A8",
    },
    fonts: { heading: "Spectral", body: "Work Sans" },
    supportsReligiousArt: false,
    religiousMotif: "none",
    defaultDesign: {
      photoPosition: "left",
      photoShape: "rounded",
      showReligiousArt: false,
      borderIntensity: 0.8,
      artworkIntensity: 0.75,
    },
  },
  {
    id: "interfaith-harmony",
    version: TEMPLATE_VERSION,
    name: "Interfaith Harmony",
    description: "Inclusive botanical artwork without religious symbols.",
    categories: ["religious-cultural", "minimal"],
    layout: "editorial",
    decoration: "botanical",
    defaultPalette: {
      bg: "#FBF9F4",
      ink: "#2A2A28",
      accent: "#6B8F71",
      muted: "#75756F",
      border: "#D5D2C6",
    },
    fonts: { heading: "Fraunces", body: "DM Sans" },
    supportsReligiousArt: false,
    religiousMotif: "none",
    defaultDesign: {
      photoPosition: "right",
      photoShape: "rounded",
      showReligiousArt: false,
      borderIntensity: 0.35,
      artworkIntensity: 0.5,
    },
  },
  {
    id: "spring-blossom",
    version: TEMPLATE_VERSION,
    name: "Spring Blossom",
    description: "Soft floral vectors and an airy garden layout for lighter documents.",
    categories: ["seasonal", "photo"],
    layout: "garden",
    decoration: "floral",
    defaultPalette: {
      bg: "#FFFCF8",
      ink: "#3A2F36",
      accent: "#D4849A",
      muted: "#8C7782",
      border: "#F0D4DC",
    },
    fonts: { heading: "Playfair Display", body: "Nunito" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "top",
      photoShape: "circle",
      borderIntensity: 0.55,
      artworkIntensity: 0.7,
      spacing: 1.2,
    },
  },
  {
    id: "summer-coast",
    version: TEMPLATE_VERSION,
    name: "Summer Coast",
    description: "Sand colours with flowing ocean lines and a coastal reading rhythm.",
    categories: ["seasonal", "modern"],
    layout: "coastal",
    decoration: "waves",
    defaultPalette: {
      bg: "#FBF7F0",
      ink: "#2A3340",
      accent: "#2F6F8F",
      muted: "#6E7A86",
      border: "#D5C7B0",
    },
    fonts: { heading: "DM Serif Display", body: "Outfit" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "left",
      photoShape: "rounded",
      borderIntensity: 0.45,
      artworkIntensity: 0.65,
    },
  },
  {
    id: "autumn-leaves",
    version: TEMPLATE_VERSION,
    name: "Autumn Leaves",
    description: "Terracotta accents with subtle leaf illustrations and warm density.",
    categories: ["seasonal"],
    layout: "classic-two-col",
    decoration: "leaves",
    defaultPalette: {
      bg: "#FFF8F2",
      ink: "#3B2418",
      accent: "#B85C38",
      muted: "#8A6554",
      border: "#E6C8B0",
    },
    fonts: { heading: "Libre Caslon Text", body: "Mulish" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "right",
      photoShape: "square",
      borderIntensity: 0.6,
      artworkIntensity: 0.6,
    },
  },
  {
    id: "winter-pearl",
    version: TEMPLATE_VERSION,
    name: "Winter Pearl",
    description: "Cool blue accents with restrained frost patterns and quiet spacing.",
    categories: ["seasonal", "minimal"],
    layout: "serene",
    decoration: "frost",
    defaultPalette: {
      bg: "#F5F8FB",
      ink: "#1F2A36",
      accent: "#5B7C99",
      muted: "#6A7785",
      border: "#C9D5E0",
    },
    fonts: { heading: "Instrument Serif", body: "Inter" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "top",
      photoShape: "circle",
      borderIntensity: 0.35,
      artworkIntensity: 0.4,
      spacing: 1.25,
    },
  },
  {
    id: "monsoon-garden",
    version: TEMPLATE_VERSION,
    name: "Monsoon Garden",
    description: "Rain-inspired lines with tropical greenery and layered garden layout.",
    categories: ["seasonal", "photo"],
    layout: "garden",
    decoration: "rain",
    defaultPalette: {
      bg: "#F3FAF6",
      ink: "#1F332C",
      accent: "#2F7A5C",
      muted: "#5F7A70",
      border: "#B7D4C6",
    },
    fonts: { heading: "Crimson Pro", body: "Figtree" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "left",
      photoShape: "rounded",
      borderIntensity: 0.5,
      artworkIntensity: 0.7,
    },
  },
  {
    id: "violet-connection",
    version: TEMPLATE_VERSION,
    name: "Violet Connection",
    description: "CupidMatch violet and coral with flowing connection-line artwork.",
    categories: ["modern"],
    layout: "asymmetric",
    decoration: "connection-lines",
    defaultPalette: {
      bg: "#FBF8F4",
      ink: "#17151D",
      accent: "#7027E8",
      muted: "#6F6979",
      border: "#EAE4EF",
    },
    fonts: { heading: "Space Grotesk", body: "Inter" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "right",
      photoShape: "rounded",
      accentColor: "#FF6F72",
      borderIntensity: 0.4,
      artworkIntensity: 0.55,
    },
  },
  {
    id: "minimal-editorial",
    version: TEMPLATE_VERSION,
    name: "Minimal Editorial",
    description: "Strong typography, generous whitespace, and an editorial reading flow.",
    categories: ["minimal", "modern"],
    layout: "editorial",
    decoration: "corner-ornament",
    defaultPalette: {
      bg: "#FFFFFF",
      ink: "#111111",
      accent: "#333333",
      muted: "#666666",
      border: "#E5E5E5",
    },
    fonts: { heading: "Newsreader", body: "Inter" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "left",
      photoShape: "square",
      borderIntensity: 0.2,
      artworkIntensity: 0.15,
      spacing: 1.35,
      fontSize: 1.05,
    },
  },
  {
    id: "geometric-balance",
    version: TEMPLATE_VERSION,
    name: "Geometric Balance",
    description: "Asymmetric vector blocks with a rounded photo and modern geometry.",
    categories: ["modern", "photo"],
    layout: "geometric",
    decoration: "geometric",
    defaultPalette: {
      bg: "#F7F5FF",
      ink: "#1A1528",
      accent: "#5B4BDB",
      muted: "#6E6788",
      border: "#D8D2F0",
    },
    fonts: { heading: "Syne", body: "Manrope" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "right",
      photoShape: "circle",
      borderIntensity: 0.55,
      artworkIntensity: 0.6,
    },
  },
  {
    id: "botanical-portrait",
    version: TEMPLATE_VERSION,
    name: "Botanical Portrait",
    description: "Large portrait hero with fine botanical line work around the margins.",
    categories: ["photo", "seasonal"],
    layout: "portrait-hero",
    decoration: "botanical",
    defaultPalette: {
      bg: "#FCFAF6",
      ink: "#2A2924",
      accent: "#557A4E",
      muted: "#737067",
      border: "#D7D2C4",
    },
    fonts: { heading: "Fraunces", body: "Source Serif 4" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "top",
      photoShape: "rounded",
      borderIntensity: 0.45,
      artworkIntensity: 0.65,
    },
  },
  {
    id: "classic-formal",
    version: TEMPLATE_VERSION,
    name: "Classic Formal",
    description: "Understated border with a structured two-column formal layout.",
    categories: ["minimal"],
    layout: "classic-two-col",
    decoration: "corner-ornament",
    defaultPalette: {
      bg: "#FFFEFB",
      ink: "#1F1C18",
      accent: "#5A4A3A",
      muted: "#6F675E",
      border: "#D9D0C4",
    },
    fonts: { heading: "Libre Baskerville", body: "Source Sans 3" },
    supportsReligiousArt: false,
    defaultDesign: {
      photoPosition: "right",
      photoShape: "square",
      borderIntensity: 0.5,
      artworkIntensity: 0.25,
      spacing: 1.05,
    },
  },
];

const byId = new Map(TEMPLATES.map((template) => [template.id, template]));

export function getTemplate(id: string): BiodataTemplateDef | undefined {
  return byId.get(id);
}
