-- Seed test profiles for development and testing
-- Creates diverse, realistic profiles with photos

-- Insert test profiles
INSERT INTO public.profiles (
  id,
  email,
  display_name,
  bio,
  photo_url,
  location,
  profession,
  dob,
  country,
  region,
  languages,
  relationship_intentions,
  values_lifestyle,
  cultural_family,
  settlement,
  is_published,
  onboarding_step,
  education_level,
  religion,
  height
) VALUES
-- Profile 1: Rajesh Kumar
(
  '01a0a652-f929-76ac-bbce-9b3f2c188d5a',
  'rajesh.kumar.test@cupidmatch.com',
  'Rajesh Kumar',
  'Software engineer passionate about technology and innovation. Love exploring new places and trying different cuisines. Looking for someone who shares my values and dreams.',
  '/profiles/01a0a652-f929-76ac-bbce-9b3f2c188d5a.jpg',
  'Colombo',
  'Software Engineer',
  '1992-03-15',
  'Sri Lanka',
  'Western Province',
  '["English", "Tamil", "Sinhala"]'::jsonb,
  '{"type": "marriage", "timeline": "1-2 years"}'::jsonb,
  '{"interests": ["Technology", "Travel", "Cooking"], "lifestyle": "Active"}'::jsonb,
  '{"family_type": "Nuclear", "living_with_family": false}'::jsonb,
  '{"preferred_countries": ["Sri Lanka", "Canada", "United Kingdom"], "open_to_relocation": true}'::jsonb,
  true,
  8,
  'Bachelors',
  'Buddhist',
  '175 cm'
),

-- Profile 2: Arun Patel
(
  '01a0a652-f947-73e7-8499-271e3c1e84d8',
  'arun.patel.test@cupidmatch.com',
  'Arun Patel',
  'Marketing professional with a love for adventure and outdoor activities. Family-oriented and looking for a life partner who values tradition and modern thinking equally.',
  '/profiles/01a0a652-f947-73e7-8499-271e3c1e84d8.jpg',
  'London',
  'Marketing Manager',
  '1990-07-22',
  'United Kingdom',
  'Greater London',
  '["English", "Tamil"]'::jsonb,
  '{"type": "marriage", "timeline": "within 1 year"}'::jsonb,
  '{"interests": ["Sports", "Reading", "Photography"], "lifestyle": "Balanced"}'::jsonb,
  '{"family_type": "Joint", "living_with_family": true}'::jsonb,
  '{"preferred_countries": ["United Kingdom", "Sri Lanka"], "open_to_relocation": false}'::jsonb,
  true,
  8,
  'Masters',
  'Hindu',
  '178 cm'
),

-- Profile 3: Dinesh Fernando
(
  '01a0a652-f963-7793-a4da-78dff528095e',
  'dinesh.fernando.test@cupidmatch.com',
  'Dinesh Fernando',
  'Doctor by profession, music enthusiast by passion. Believe in building meaningful connections based on mutual respect and understanding.',
  '/profiles/01a0a652-f963-7793-a4da-78dff528095e.jpg',
  'Toronto',
  'Medical Doctor',
  '1988-11-08',
  'Canada',
  'Ontario',
  '["English", "Sinhala"]'::jsonb,
  '{"type": "marriage", "timeline": "2-3 years"}'::jsonb,
  '{"interests": ["Music", "Healthcare", "Volunteering"], "lifestyle": "Professional"}'::jsonb,
  '{"family_type": "Nuclear", "living_with_family": false}'::jsonb,
  '{"preferred_countries": ["Canada", "Sri Lanka", "United States"], "open_to_relocation": true}'::jsonb,
  true,
  8,
  'Doctorate',
  'Catholic',
  '180 cm'
),

-- Profile 4: Karthik Reddy
(
  '01a0a652-f983-72ec-95e5-6a2f6cafa0ce',
  'karthik.reddy.test@cupidmatch.com',
  'Karthik Reddy',
  'Finance analyst who enjoys good conversations over coffee. Looking for someone to build a future with, filled with love, laughter, and shared dreams.',
  '/profiles/01a0a652-f983-72ec-95e5-6a2f6cafa0ce.jpg',
  'Melbourne',
  'Finance Analyst',
  '1993-05-30',
  'Australia',
  'Victoria',
  '["English", "Tamil"]'::jsonb,
  '{"type": "marriage", "timeline": "1-2 years"}'::jsonb,
  '{"interests": ["Finance", "Travel", "Food"], "lifestyle": "Urban"}'::jsonb,
  '{"family_type": "Nuclear", "living_with_family": false}'::jsonb,
  '{"preferred_countries": ["Australia", "Sri Lanka", "Singapore"], "open_to_relocation": true}'::jsonb,
  true,
  8,
  'Masters',
  'Hindu',
  '172 cm'
),

-- Profile 5: Vikram Silva
(
  '01a0a652-f9a1-736d-93cf-ac7f98096303',
  'vikram.silva.test@cupidmatch.com',
  'Vikram Silva',
  'Entrepreneur passionate about sustainability and social impact. Love hiking, reading, and meaningful conversations. Seeking a partner who shares similar values.',
  '/profiles/01a0a652-f9a1-736d-93cf-ac7f98096303.jpg',
  'Kandy',
  'Business Owner',
  '1991-09-12',
  'Sri Lanka',
  'Central Province',
  '["English", "Sinhala", "Tamil"]'::jsonb,
  '{"type": "marriage", "timeline": "within 1 year"}'::jsonb,
  '{"interests": ["Business", "Environment", "Fitness"], "lifestyle": "Active"}'::jsonb,
  '{"family_type": "Joint", "living_with_family": true}'::jsonb,
  '{"preferred_countries": ["Sri Lanka", "Singapore"], "open_to_relocation": false}'::jsonb,
  true,
  8,
  'Bachelors',
  'Buddhist',
  '176 cm'
),

-- Profile 6: Priya Jayawardena
(
  '01a0a652-f9c1-70ff-9eef-ad297f2281b0',
  'priya.jayawardena.test@cupidmatch.com',
  'Priya Jayawardena',
  'Teacher who believes in lifelong learning and personal growth. Family is important to me, and I value traditions while embracing modernity.',
  '/profiles/01a0a652-f9c1-70ff-9eef-ad297f2281b0.jpg',
  'Jaffna',
  'School Teacher',
  '1994-02-18',
  'Sri Lanka',
  'Northern Province',
  '["Tamil", "English"]'::jsonb,
  '{"type": "marriage", "timeline": "1-2 years"}'::jsonb,
  '{"interests": ["Education", "Arts", "Community"], "lifestyle": "Traditional"}'::jsonb,
  '{"family_type": "Joint", "living_with_family": true}'::jsonb,
  '{"preferred_countries": ["Sri Lanka", "Canada"], "open_to_relocation": true}'::jsonb,
  true,
  8,
  'Bachelors',
  'Hindu',
  '160 cm'
),

-- Profile 7: Anjali Perera
(
  '01a0a652-f9e0-76ea-bb5b-13ce9e54cca5',
  'anjali.perera.test@cupidmatch.com',
  'Anjali Perera',
  'IT professional working in cybersecurity. Love solving puzzles, both technical and in daily life. Looking for someone intelligent, kind, and family-oriented.',
  '/profiles/01a0a652-f9e0-76ea-bb5b-13ce9e54cca5.jpg',
  'Sydney',
  'Cybersecurity Specialist',
  '1992-08-25',
  'Australia',
  'New South Wales',
  '["English", "Sinhala"]'::jsonb,
  '{"type": "marriage", "timeline": "2-3 years"}'::jsonb,
  '{"interests": ["Technology", "Chess", "Yoga"], "lifestyle": "Balanced"}'::jsonb,
  '{"family_type": "Nuclear", "living_with_family": false}'::jsonb,
  '{"preferred_countries": ["Australia", "Sri Lanka", "New Zealand"], "open_to_relocation": true}'::jsonb,
  true,
  8,
  'Masters',
  'Buddhist',
  '165 cm'
),

-- Profile 8: Nithya Rajan
(
  '01a0a652-f9ff-7f68-ad79-59442a3508bf',
  'nithya.rajan.test@cupidmatch.com',
  'Nithya Rajan',
  'Architect passionate about sustainable design and cultural heritage. Looking for a life partner who appreciates art, culture, and meaningful connections.',
  '/profiles/01a0a652-f9ff-7f68-ad79-59442a3508bf.jpg',
  'Dubai',
  'Architect',
  '1991-06-14',
  'United Arab Emirates',
  'Dubai',
  '["English", "Tamil", "Sinhala"]'::jsonb,
  '{"type": "marriage", "timeline": "1-2 years"}'::jsonb,
  '{"interests": ["Architecture", "Art", "Travel"], "lifestyle": "Creative"}'::jsonb,
  '{"family_type": "Nuclear", "living_with_family": false}'::jsonb,
  '{"preferred_countries": ["Sri Lanka", "United Arab Emirates", "United Kingdom"], "open_to_relocation": true}'::jsonb,
  true,
  8,
  'Masters',
  'Hindu',
  '162 cm'
),

-- Profile 9: Kavya Mendis
(
  '01a0a652-fa20-782a-9f96-1a38d12e7135',
  'kavya.mendis.test@cupidmatch.com',
  'Kavya Mendis',
  'Healthcare administrator dedicated to improving patient care. Enjoy cooking, gardening, and spending time with family. Seeking someone with similar values.',
  '/profiles/01a0a652-fa20-782a-9f96-1a38d12e7135.jpg',
  'Galle',
  'Healthcare Administrator',
  '1993-12-03',
  'Sri Lanka',
  'Southern Province',
  '["Sinhala", "English"]'::jsonb,
  '{"type": "marriage", "timeline": "within 1 year"}'::jsonb,
  '{"interests": ["Healthcare", "Cooking", "Gardening"], "lifestyle": "Homely"}'::jsonb,
  '{"family_type": "Joint", "living_with_family": true}'::jsonb,
  '{"preferred_countries": ["Sri Lanka"], "open_to_relocation": false}'::jsonb,
  true,
  8,
  'Bachelors',
  'Buddhist',
  '158 cm'
),

-- Profile 10: Roshini Kumar
(
  '01a0a652-fa40-7ce7-836a-e84608163af4',
  'roshini.kumar.test@cupidmatch.com',
  'Roshini Kumar',
  'Data scientist fascinated by AI and machine learning. Love solving complex problems and learning new things. Looking for someone who values growth and partnership.',
  '/profiles/01a0a652-fa40-7ce7-836a-e84608163af4.jpg',
  'Singapore',
  'Data Scientist',
  '1990-04-20',
  'Singapore',
  'Singapore',
  '["English", "Tamil"]'::jsonb,
  '{"type": "marriage", "timeline": "2-3 years"}'::jsonb,
  '{"interests": ["Data Science", "Learning", "Travel"], "lifestyle": "Professional"}'::jsonb,
  '{"family_type": "Nuclear", "living_with_family": false}'::jsonb,
  '{"preferred_countries": ["Singapore", "Sri Lanka", "United States"], "open_to_relocation": true}'::jsonb,
  true,
  8,
  'Masters',
  'Hindu',
  '163 cm'
)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  bio = EXCLUDED.bio,
  photo_url = EXCLUDED.photo_url,
  location = EXCLUDED.location,
  profession = EXCLUDED.profession,
  is_published = EXCLUDED.is_published;

-- Grant RLS policies will apply automatically
